SAMPLING = 1
POISSON_DEPTH = 8

DEFAULT_INPUT_DIR = "../data"
DEFAULT_OUTPUT_DIR = r"../output"
DEFAULT_OUTPUT_FILE = r"MyMould"
POISSON_RECONSTRUCTOR_EXECUTABLE = "../bin/PoissonRecon"
BLOCKSIZE = 100

MOULD_THICKNESS = 10
